# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch


# Create random tensor
import torch
tensor_A = torch.rand(7,7)
tensor_A


tensor([[0.2370, 0.3688, 0.6290, 0.7106, 0.5427, 0.0330, 0.2863],
        [0.1922, 0.3913, 0.2049, 0.3948, 0.0425, 0.2921, 0.6167],
        [0.3895, 0.2832, 0.9313, 0.7866, 0.8992, 0.6874, 0.2583],
        [0.8163, 0.8801, 0.8298, 0.5806, 0.5409, 0.4724, 0.7706],
        [0.2652, 0.4708, 0.9819, 0.3049, 0.4362, 0.7696, 0.5354],
        [0.3630, 0.4414, 0.5657, 0.7747, 0.9935, 0.4008, 0.5823],
        [0.1466, 0.8688, 0.4927, 0.1658, 0.9936, 0.9270, 0.3826]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor

# Perform matrix multiplication
import torch

tensor_B = torch.rand(1,7)
print(f"Tensor_A:\n{tensor_A}\n")
print(f"Tensor_B:\n{tensor_B}\n")
print(f"Tensor_B.Transpose\n{tensor_B.T}\n")
tensor_multiply = torch.matmul(tensor_A, tensor_B.T)
print(f"Tensor_A * Tensor_B.T:\n {tensor_multiply}\n")


Tensor_A:
tensor([[0.2370, 0.3688, 0.6290, 0.7106, 0.5427, 0.0330, 0.2863],
        [0.1922, 0.3913, 0.2049, 0.3948, 0.0425, 0.2921, 0.6167],
        [0.3895, 0.2832, 0.9313, 0.7866, 0.8992, 0.6874, 0.2583],
        [0.8163, 0.8801, 0.8298, 0.5806, 0.5409, 0.4724, 0.7706],
        [0.2652, 0.4708, 0.9819, 0.3049, 0.4362, 0.7696, 0.5354],
        [0.3630, 0.4414, 0.5657, 0.7747, 0.9935, 0.4008, 0.5823],
        [0.1466, 0.8688, 0.4927, 0.1658, 0.9936, 0.9270, 0.3826]])

Tensor_B:
tensor([[0.2192, 0.7993, 0.5931, 0.0135, 0.6815, 0.9956, 0.0851]])

Tensor_B.Transpose
tensor([[0.2192],
        [0.7993],
        [0.5931],
        [0.0135],
        [0.6815],
        [0.9956],
        [0.0851]])

Tensor_A * Tensor_B.T:
 tensor([[1.1564],
        [0.8540],
        [2.1938],
        [2.2870],
        [2.1300],
        [1.9040],
        [2.6536]])



### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors

tensor_C = torch.rand(7,7)
tensor_D = torch.rand(1,7)

# Matrix multiply tensors

new_tensor_multiply = torch.matmul(tensor_C, tensor_D.T)
new_tensor_multiply, new_tensor_multiply.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
import torch
torch.manual_seed(1234)

# Check for access to GPU

device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Create two random tensors on GPU
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)

print(f'Tensor one: device {tensor_A.device}')
print(f'Tensor two: device {tensor_B.device}')
print()
tensor_A_gpu = tensor_A.to(device)
tensor_B_gpu = tensor_B.to(device)

print(f'Tensor one device changed to: {tensor_A_gpu.device}')
print(f'Tensor two device changed to: {tensor_B_gpu.device}')


Tensor one: device cpu
Tensor two: device cpu

Tensor one device changed to: cuda:0
Tensor two device changed to: cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor_cuda_matmul = torch.matmul(tensor_A_gpu, tensor_B_gpu.T)
tensor_cuda_matmul, tensor_cuda_matmul.size()

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
tensor_max = torch.max(tensor_cuda_matmul)

# Find min
tensor_min = torch.min(tensor_cuda_matmul)

print(f"tensor maximum value: {tensor_max}")
print(f"tensor minimum value: {tensor_min}")

tensor maximum value: 0.5617256760597229
tensor minimum value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
tensor_arg_max = tensor_cuda_matmul.argmax()

# Find arg min
tensor_arg_min = tensor_cuda_matmul.argmin()

print(f"tensor arg maximum value: {tensor_arg_max}")
print(f"tensor arg minimum value: {tensor_arg_min}")

tensor arg maximum value: 3
tensor arg minimum value: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
import torch
torch.manual_seed(7)

# Create random tensor
tensor_random_A = torch.rand(1,1,1,10)


# Remove single dimensions
tensor_random_B = tensor_random_A.squeeze()

# Print out tensors and their shapes
print(f'tensor A: {tensor_random_A, tensor_random_A.size()}')
print(f'tensor B: {tensor_random_B, tensor_random_B.size()}')

tensor A: (tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))
tensor B: (tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
